### ISSUE TITLE
Mapa mental Yuliana 1AS

### ISSUE THREAD

**Issue by YulianaMorales18** [SistemasTecTlaxiaco/actividad-4-mapa-mental-YulianaMorales18#2]
[Mapa mental yuliana.pdf](https://github.com/user-attachments/files/17104330/Mapa.mental.yuliana.pdf)

**Comment by irwingsael** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:5/5
Referencias:5/5
Calificación Final:20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
